# Generated by Django 5.1.5 on 2025-02-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_criteria_evaluation_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
